version: "3.9"

services:
  mariadb:
    image: mariadb:11
    container_name: petstore-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: PETSTORE
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "3303:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - petnet
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  petstore-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
      - ./secrets/pomodorio-gcs-key.json:/app/secrets/pomodorio-gcs-key.json:ro
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_PROFILES_ACTIVE: prod
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      GCP_BUCKET_URL: ${GCP_BUCKET_URL}
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      GOOGLE_APPLICATION_CREDENTIALS: /app/secrets/pomodorio-gcs-key.json
    networks:
      - petnet
    restart: unless-stopped

  petstore-frontend:
    build:
      context: ./petstore-ui
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "443:443"
    depends_on:
      - petstore-backend
    networks:
      - petnet
    restart: unless-stopped

volumes:
  mariadb_data:
  uploads:

networks:
  petnet:
    driver: bridge