version: '3.8'

services:
  app:
    image: petstore
    build:
      context: .
    container_name: petstore-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/PETSTORE
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: petstore-db
    environment:

      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: PETSTORE
      MARIADB_USER: root
      MARIADB_PASSWORD: password
    ports:
      - "3303:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
