server:
  port: 8443
  ssl:
    key-alias: https-pomodorio
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: password

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/PETSTORE
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: password
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: CLIENT_ID
            client-secret: CLIENT_SECRET
            redirect-uri: "https://localhost:8443/login/oauth2/code/google"
            scope: openid,profile,email
            authorization-grant-type: authorization_code
        provider:
          google:
            issuer-uri: https://accounts.google.com
