server:
  port: 8443
  ssl:
    key-alias: https-pomodorio
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEYSTORE_PASSWORD}

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/PETSTORE
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openId,profile,email
            authorization-grant-type: authorization_code
        provider:
          google:
            issuer-uri: https://accounts.google.com

logging:
  level:
    org.springframework.web: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000