server:
  port: 8443
  ssl:
    key-alias: https-pomodorio
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: password



spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/PETSTORE?allowPublicKeyRetrieval=true&useSSL=false
    driverClassName: org.mariadb.jdbc.Driver
    username: root
    password: password